<?php

namespace AppBundle\Repository;

/**
 * ActionCaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionCaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
