<?php

namespace AppBundle\Repository;

/**
 * ArrivageProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivageProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
