<?php

namespace AppBundle\Repository;

/**
 * ArrivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivageRepository extends \Doctrine\ORM\EntityRepository
{
}
