<?php

namespace AppBundle\Repository;

/**
 * ArrivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivageRepository extends \Doctrine\ORM\EntityRepository
{

  public function findTodayArrivages(){
    return  $this->createQueryBuilder('A')
                  ->select('A')
                  ->andWhere('A.dateCreation > :date')
                  ->andWhere('A.dateCreation < :date2')
                  ->setParameter('date', new \DateTime('today'))
                  ->setParameter('date2', new \DateTime('tomorrow'))
                  ->getQuery()
                  ->getResult();
  }

}
