<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
  public function findClientCredit(){
    return  $this->createQueryBuilder('c')
                  ->select('c')
                  ->andWhere('c.plusOuMoins < 0')
                  ->orderBy('c.plusOuMoins', 'ASC')
                  // ->andWhere('p.date < :date2')
                  // ->setParameter('date', new \DateTime('today'))
                  // ->setParameter('date2', new \DateTime('tomorrow'))
                  ->getQuery()
                  ->getResult();
  }
}
