<?php

namespace AppBundle\Repository;

/**
 * ArrivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardRepository extends \Doctrine\ORM\EntityRepository
{
  public function countClient(){
    $qb = $this->createQueryBuilder();
    $qb->select('count(c.id)')
       ->from('AppBundle:Client', 'c');
       // ->where('u.id = ?1')
       // ->orderBy('u.name', 'ASC');
    return $qb->getQuery();

  }
}
