<?php

namespace AppBundle\Repository;

/**
 * ElementCaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementCaisseRepository extends \Doctrine\ORM\EntityRepository
{

  public function findAll()
  {
      return $this->findBy(array(), array('date' => 'DESC'));
  }

  public function findLastElementCaisse() {
  $qb = $this->createQueryBuilder('ec');
  $qb->setMaxResults( 1 );
  $qb->orderBy("ec.date", "DESC");
  return $qb->getQuery()->getResult();
  }
}
