<?php

namespace AppBundle\Repository;

/**
 * ElementArrivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementArrivageRepository extends \Doctrine\ORM\EntityRepository
{
}
