<?php

namespace AppBundle\Repository;

/**
 * PayementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayementRepository extends \Doctrine\ORM\EntityRepository
{
  public function payementByClientId($id)
  {
      // return $this->getEntityManager()
      //     ->createQuery('
      //         SELECT p. FROM AppBundle:Payement p
      //         where p.client = '.$id.'
      //     ')
      //     //ORDER BY p.quantite ASC
      //     ->getResult();

      return  $this->createQueryBuilder('p')
                    ->andWhere('p.client = :id')
                    ->setParameter('id', $id)
                    ->select('SUM(p.montant) as Total')
                    ->getQuery()
                    ->getOneOrNullResult();
  }

  public function findTodayPayements(){
      return  $this->createQueryBuilder('p')
                    ->select('p')
                    ->andWhere('p.date > :date')
                    ->andWhere('p.date < :date2')
                    ->setParameter('date', new \DateTime('today'))
                    ->setParameter('date2', new \DateTime('tomorrow'))
                    ->getQuery()
                    ->getResult();
  }

  public function findChequesNonPayes(){
    return  $this->createQueryBuilder('p')
                  ->select('p')
                  ->andWhere("p.type = 'cheque'")
                  ->andWhere('p.etatCheque = 0')
                  ->orderBy("p.dateCheque","ASC")
                  ->getQuery()
                  ->getResult();
  }

}
